[package]

name = "rcstring"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-rcstring.git"
description = "Reference counted strings and slices."
readme = "README.md"
license = "MIT"

